### ISSUE TITLE
Error when rig "test" is opened

### ISSUE THREAD

**Issue by 68Duck** [68Duck/PiDMX#58]
<class 'AttributeError'> 'RGB6Channel' object has no attribute 'lightInformation' <traceback object at 0x00E1AFE8>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\openRigWindow.py", line 58, in openButtonClicked
    self.openRig()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\openRigWindow.py", line 95, in openRig
    self.displayOnWindow(self.newLight,xpos,ypos,lightType,startChannel)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\openRigWindow.py", line 99, in displayOnWindow
    self.visualLightDisplay.createLightFromSavedRig(light,xpos,ypos,lightType,channel)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\lightDisplayWindow.py", line 365, in createLightFromSavedRig
    self.newLight = DatabaseDisplayLight(xpos,ypos,channel,self.lightDisplay,self)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\displayLightTypes.py", line 120, in __init__
    self.lightInformation = light.lightInformation
AttributeError: 'RGB6Channel' object has no attribute 'lightInformation'
<class 'AttributeError'> 'RGB6Channel' object has no attribute 'lightInformation' <traceback object at 0x00E1AD88>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\openRigWindow.py", line 58, in openButtonClicked
    self.openRig()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\openRigWindow.py", line 95, in openRig
    self.displayOnWindow(self.newLight,xpos,ypos,lightType,startChannel)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\openRigWindow.py", line 99, in displayOnWindow
    self.visualLightDisplay.createLightFromSavedRig(light,xpos,ypos,lightType,channel)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\lightDisplayWindow.py", line 365, in createLightFromSavedRig
    self.newLight = DatabaseDisplayLight(xpos,ypos,channel,self.lightDisplay,self)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\displayLightTypes.py", line 120, in __init__
    self.lightInformation = light.lightInformation
AttributeError: 'RGB6Channel' object has no attribute 'lightInformation'

**Comment by 68Duck** [comment]
I don't think this is a problem anymore?

**Comment by 68Duck** [comment]
Only happens when swapping between rigs e.g. houseMusic to test?

**Comment by 68Duck** [comment]
Issue fixed
