### ISSUE TITLE
Computer dmx

### ISSUE THREAD

**Issue by 68Duck** [68Duck/PiDMX#62]
If cable is not plugged in this happens:

<class 'Exception'> The serial is not working. Please make sure the lights are plugged in and that you don't have any other dmx scripts running and make sure the port is correct <traceback object at 0x0D152968>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\pydmx.py", line 59, in __init__
    self.ser = serial.Serial(port,baudrate)
  File "C:\Users\Joshu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Joshu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Joshu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\portSelectionWindow.py", line 27, in testButtonPressed
    dmx = PyDMX(port)
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\pydmx.py", line 62, in __init__
    raise Exception("The serial is not working. Please make sure the lights are plugged in and that you don't have any other dmx scripts running and make sure the port is correct")
Exception: The serial is not working. Please make sure the lights are plugged in and that you don't have any other dmx scripts running and make sure the port is correct

**Comment by 68Duck** [comment]
Now deals with the error when it is pulled and then checks to see if works until plugged in again so then works when plugged in again
