### ISSUE TITLE
Looping sequences

### ISSUE THREAD

**Issue by 68Duck** [68Duck/PiDMX#67]
:(
<class 'KeyError'> 2 <traceback object at 0x0168F188>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 33, in openButtonClicked
    self.setupSequence()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 53, in setupSequence
    self.runSequence()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 70, in runSequence
    self.firstTimeDelay = self.sequenceToOpen[0][2]
KeyError: 2
<class 'KeyError'> 2 <traceback object at 0x0168F2A8>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 33, in openButtonClicked
    self.setupSequence()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 53, in setupSequence
    self.runSequence()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 70, in runSequence
    self.firstTimeDelay = self.sequenceToOpen[0][2]
KeyError: 2

**Comment by 68Duck** [comment]
Fixed
