### ISSUE TITLE
Sequence testing

### ISSUE THREAD

**Issue by 68Duck** [68Duck/PiDMX#71]
Test that the change colour according to fixture is working so check if the sequence saves properly and opens in the same colour

**Comment by 68Duck** [comment]
Found this when using the pressure test to test this:
<class 'AttributeError'> 'SequenceDisplayLight' object has no attribute 'light' <traceback object at 0x0DEF7EC8>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceWindow.py", line 100, in nextPlaybackButtonClicked
    self.openPlayback()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceWindow.py", line 128, in openPlayback
    displayLight.changeColourAccordingToFixture()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceDisplayLightTypes.py", line 251, in changeColourAccordingToFixture
    red = hex(self.light.red)
AttributeError: 'SequenceDisplayLight' object has no attribute 'light'

**Comment by 68Duck** [comment]
Hopefully issue fixed
