### ISSUE TITLE
Opening saved playbacks

### ISSUE THREAD

**Issue by 68Duck** [68Duck/PiDMX#78]
When opening a saved sequence with an effect this error is produced:
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 32, in openButtonClicked
    del self.visualLightDisplay.sequenceSelectionWindowCopy
AttributeError: sequenceSelectionWindowCopy
<class 'AttributeError'> sequenceSelectionWindowCopy <traceback object at 0x0C813468>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\sequenceSelectionWindow.py", line 32, in openButtonClicked
    del self.visualLightDisplay.sequenceSelectionWindowCopy
AttributeError: sequenceSelectionWindowCopy
<class 'AttributeError'> 'EffectsWindow' object has no attribute 'rainbowIO' <traceback object at 0x0C819E88>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\playbackWindow.py", line 44, in runButtonClicked
    self.executePlayback()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\playbackWindow.py", line 73, in executePlayback
    self.visualLightDisplay.effectsWindow.rainbowIO[0].setChecked(True)
AttributeError: 'EffectsWindow' object has no attribute 'rainbowIO'
<class 'AttributeError'> 'EffectsWindow' object has no attribute 'rainbowIO' <traceback object at 0x0C813668>
Traceback (most recent call last):
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\playbackWindow.py", line 44, in runButtonClicked
    self.executePlayback()
  File "C:\Users\Joshu\OneDrive\Documents\python new comp\dmxTest\PiDMX\PiDMX\playbackWindow.py", line 73, in executePlayback
    self.visualLightDisplay.effectsWindow.rainbowIO[0].setChecked(True)
AttributeError: 'EffectsWindow' object has no attribute 'rainbowIO'

**Comment by 68Duck** [comment]
Supposedly fixed?
